export const imageItems = [
    {
      id: 1,
      src: '/assets/images/carousel-5.png',
      alt: 'Dental Procedure',
      category: 'procedures',
      caption: 'Teeth Whitening Treatment',
    },
    {
      id: 2,
      src: '/assets/images/carousel-5.png',
      alt: 'Before and After',
      category: 'before-after',
      caption: 'Smile Transformation',
    },
    {
      id: 3,
      src: '/assets/images/carousel-5.png',
      alt: 'Patient Testimonial',
      category: 'testimonials',
      caption: '"Excellent service and care!"',
    },
    {
      id: 4,
      src: '/assets/images/carousel-5.png',
      alt: 'Clinic Facility',
      category: 'facilities',
      caption: 'State-of-the-art Sterilization',
    },
    {
      id: 5,
      src: '/assets/images/carousel-5.png',
      alt: 'Staff Photo',
      category: 'staff',
      caption: 'Our Friendly Dental Team',
    },
    {
      id: 6,
      src: '/assets/images/carousel-5.png',
      alt: 'Dental Procedure',
      category: 'procedures',
      caption: 'Dental Implant Placement',
    },
    {
      id: 7,
      src: '/assets/images/carousel-5.png',
      alt: 'Before and After',
      category: 'before-after',
      caption: 'Gum Reshaping Transformation',
    },
    {
      id: 8,
      src: '/assets/images/carousel-5.png',
      alt: 'Patient Testimonial',
      category: 'testimonials',
      caption: '"Highly recommended!"',
    },
    {
      id: 9,
      src: '/assets/images/carousel-5.png',
      alt: 'Clinic Facility',
      category: 'facilities',
      caption: 'Modern Dental Equipment',
    },
    {
      id: 10,
      src: '/assets/images/carousel-5.png',
      alt: 'Staff Photo',
      category: 'staff',
      caption: 'Our Experienced Dentists',
    },
  ];