export const imageItems = [
  {
    id: 1,
    src: '/assets/images/carousel-5.png',
    alt: 'Dental Procedure',
    category: 'procedures',
    caption: 'Teeth Whitening Treatment',
    description: 'A comprehensive teeth whitening procedure to brighten your smile and boost your confidence.',
  },
  {
    id: 2,
    src: '/assets/images/carousel-5.png',
    alt: 'Before and After',
    category: 'before-after',
    caption: 'Smile Transformation',
    description:
      'Witness the amazing transformation of a patient’s smile after a series of cosmetic dental treatments.',
  },
  {
    id: 3,
    src: '/assets/images/carousel-5.png',
    alt: 'Patient Testimonial',
    category: 'testimonials',
    caption: '"Excellent service and care!"',
    description: 'Hear from our satisfied patients about the exceptional care they received at our clinic.',
  },
  {
    id: 4,
    src: '/assets/images/carousel-5.png',
    alt: 'Clinic Facility',
    category: 'facilities',
    caption: 'State-of-the-art Sterilization',
    description:
      'Our clinic is equipped with the latest sterilization technology to ensure a safe and clean environment.',
  },
  {
    id: 5,
    src: '/assets/images/carousel-5.png',
    alt: 'Staff Photo',
    category: 'staff',
    caption: 'Our Friendly Dental Team',
  },
  {
    id: 6,
    src: '/assets/images/carousel-5.png',
    alt: 'Dental Procedure',
    category: 'procedures',
    caption: 'Dental Implant Placement',
    description: 'A detailed look at the dental implant placement procedure, ensuring long-lasting results.',
  },
  {
    id: 7,
    src: '/assets/images/carousel-5.png',
    alt: 'Before and After',
    category: 'before-after',
    caption: 'Gum Reshaping Transformation',
    description: 'See the difference our gum reshaping procedure can make for a healthier, more attractive smile.',
  },
  {
    id: 8,
    src: '/assets/images/carousel-5.png',
    alt: 'Patient Testimonial',
    category: 'testimonials',
    caption: '"Highly recommended!"',
    description: 'Discover why our patients highly recommend our dental services to their friends and family.',
  },
  {
    id: 9,
    src: '/assets/images/carousel-5.png',
    alt: 'Clinic Facility',
    category: 'facilities',
    caption: 'Modern Dental Equipment',
    description: 'We use state-of-the-art dental equipment to provide the best care possible.',
  },
  {
    id: 10,
    src: '/assets/images/carousel-5.png',
    alt: 'Staff Photo',
    category: 'staff',
    caption: 'Our Experienced Dentists',
  },
];
